---
example:
  property: I AM DEV-A

server:
  port: 8080

spring:
  profiles: dev-a
  config:
    import: optional:configserver:http://config-server:8070   
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-01:5070/eureka/,http://eureka-server-02:5070/eureka/
      

---
example:
  property: I AM DEV-B

server:
  port: 8070
  
spring:
  profiles: dev-b
  config:
    import: optional:configserver:http://config-server:8070

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-03:5070/eureka/,http://eureka-server-04:5070/eureka/
