---
example:
  property: I AM DEFAULT
  
spring:
  profiles: default
server:
  port: 8080

spring:
  application:
    name: apigateway-demo

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5070/eureka/
    

---
example:
  property: I AM DEV-A
  
spring:
  profiles: dev-a
server:
  port: 8080

spring:
  application:
    name: apigateway-demo

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-01:5070/eureka/,http://eureka-server-02:5070/eureka/


---
example:
  property: I AM DEV-B
  
spring:
  profiles: dev-b
server:
  port: 8080

spring:
  application:
    name: apigateway-demo

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-03:5070/eureka/,http://eureka-server-04:5070/eureka/
