---
spring:
  profiles: dev-a
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-01:5070/eureka/,http://eureka-server-02:5070/eureka/
      
example:
  property: I AM DEV-A

---
spring:
  profiles: dev-b

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-03:5070/eureka/,http://eureka-server-04:5070/eureka/
      
example:
  property: I AM DEV-B
